version: '3'

services:
  evilginx2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evilginx2
    ports:
      - 8080:80/tcp
      - 8443:443/tcp
    #command: ["/bin/bash"]
    command: ["/bin/evilginx", "-p", "/app/phishlets", "-debug"]
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/evilginx2/phishlets:/app/phishlets
    stdin_open: true
    tty: true
